version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
      timezone: America/Chicago
    open-pull-requests-limit: 10
    target-branch: develop
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
      timezone: America/Chicago
    open-pull-requests-limit: 10
    target-branch: develop
